name: Build & Create GitHub Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    uses: SLNE-Development/surf-workflows/.github/workflows/build-publish-release-gradle.yml@master
    with:
      modules: "surf-serverbrand-customizer-*.jar"
    secrets: inherit